services:
  - type: web
    name: football-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py --server.port=10000 --server.address=0.0.0.0
    plan: free
